#MossMirai机器人框架配置文件
#Powered by mirai
#Design by MossCG

#机器人基本设置
#账号密码
botNumber: 114514
botPassword: 123456
#机器人默认指令前缀
botCommandPrefix: "#"
#机器人文件存储位置
botFile: ./MossMirai/bot
#机器人是否显示日志
botMainLog: false
botNetworkLog: false
#开启的群
botGroups: "1072507973,779291908"
#管理权限用户
botAdmins: "1292141077"
#机器人心跳策略（1-STAT_HB、2-REGISTER、3-NONE）
botHeartbeat: 1
#机器人登陆协议（1-ANDROID_PHONE、2-ANDROID_PAD、3-ANDROID_WATCH）
botProtocol: 1
#机器人是否只回复一条信息
#避免指令和关键词或自动回复有相同内容导致多回复
#回复优先级：指令>自动回复>关键词
botOnlyOneReply: true
#机器人是否会提示未知指令及无权限
botUnknownCommand: false

#是否绕过windows的启动参数判断
#用来避免之间点开jar导致无界面运行
#甚至还不会关的情况的
systemCheckPass: true